### ISSUE TITLE
The Github Unity tool cannot be committed to version control

### ISSUE THREAD

**Issue by kinifi** [github-beta/unity-preview#18]
Version: 5.6.0f3
Github For Windows Version: v0.9.1-alpha
Platform: Windows 10

Steps to Reproduce:
1. Init a new repro
2. Select the Changes Tab 
3. Observe, the files you can commit do not include the Github Unity tool because it is looking for a Editor file in your root. If you create a Github Folder and move Editor into it (which is fine in Unity 5.0 and above), you can then commit it to version control so everyone in your team now has the Github For Unity Tool.

**Comment by shana** [comment]
hey @kinifi 

There's a reason why we set the `.gitignore` file to ignore the GitHub for Unity folder - GitHub for Unity is currently in early alpha, so installing it should be an explicit opt-in choice by the user. This is also the reason why we're doing the alpha here and not in the Unity asset store, so that people that are using GitHub for Unity are fully aware of the state of the project. Pushing the extension to the repository can lead to others downloading it without being aware that it's there or what it can and cannot do, and that is a big no-no with alpha software.

**Comment by shana** [comment]
Update: we'll likely be inverting the folder order so it's `GitHub/Editor` instead of `Editor/GitHub`, to make it simpler and reduce meta file waste. We'll still be configuring it to be ignored for now, at least until it's more stable.
