### ISSUE TITLE
Reduce initialization log output

### ISSUE THREAD

**Issue by jessemcculloch** [github-beta/unity-preview#40]
It would be super helpful to have a flag that can be turned on to write the debug statements to the Unity Console, but that we can turn off so that there is not a bunch of Unity GitHub log statements for me to try and parse through as I am working on my app.  At this point there are so many that I don't bother to look at them anyways, so I don't feel like they are doing that much good.

**Comment by StanleyGoldman** [comment]
Hey @jessemcculloch thanks again for the feedback.

We have an idea coming down the pipeline, where we will show you give you a specific display that will show the git commands that are being run on your behalf. I think that is what you are looking for.

We also have a file log, which really only logs startup. Unless you tick "Trace Logging" in Settings, then it logs an exorbitant amount of information. We were scared of filling hard drives, so that's why we added that checkbox there, but it's a trace log, so it's in far too much detail to be of use to you when programming.

wdyt?

**Comment by jessemcculloch** [comment]
Those sound like great enhancements, however this is what I am talking about.  Notice all the statements that you guys are writing to the console?  I want a flag or setting where I can turn those off, cause they kind of clutter up my console for development.

![image](https://cloud.githubusercontent.com/assets/11747005/25822222/c2468374-33ec-11e7-93ab-8dbc6a4f589a.png)

**Comment by StanleyGoldman** [comment]
Ahh... I understand what you are saying now...
I'm going to tweak the bug title of the issue you created.

**Comment by jessemcculloch** [comment]
Sure.  Thanks!

**Comment by StanleyGoldman** [comment]
Hey @jessemcculloch there is a new repo that is open sourced and a new build out. It fixes this issue.
https://github.com/github-for-unity/Unity
